# Introducción a la ciencia de datos

## Tarea 3 : Algunos ejercicios de Numpy

### Ejercicio 1
- Crea un arreglo con tres elementos y obtén con la función del `sin()` de Numpy los valores correspondientes, los cuales deben ser almacenados en otro vector para ser impresos.


In [25]:
import numpy as np

# Vamos a crear un arreglo de 3 elementos

array = np.array([0,90,180])* np.pi/180 # Nota: Convertimos las entradas del arreglo a radianes
sinArray = np.sin(array) # Aplicamos la función seno a cada elemento del arreglo
print(sinArray) #imprimimos el arreglo sinarreglo


[0.0000000e+00 1.0000000e+00 1.2246468e-16]


- Realiza la misma operación, pero por un camino largo:
  - Ejecuta un loop en el que cada uno de los elementos del arreglo inicial es transformado con el `sin()`.

In [35]:

# creamos un np.array vacío
sinArrayEmpty = np.array([])

for element in array:
    sinArrayEmpty = np.append(sinArrayEmpty, np.sin(element)) # agregamos el seno de cada elemento del arreglo array al arreglo sinArrayEmpty
    print(sinArrayEmpty) # imprimimos el arreglo sinArrayEmpty para ver como se va llenando



[0.]
[0. 1.]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]


### Ejercicio 2

- Considera un polinomio de orden N. Escribe un programa con arreglos y métodos de Numpy. 
- Implementa una función en la que se use el método `cumprod()`. 
  
- Invoca a la función asignando un valor a la variable (x) y los coeficientes asociados del polinomio correspondiente (Ojo: si `N = 2`, debe haber tres coeficientes ya que hay un término constante). 

- Estos coeficientes deben formar parte de un arreglo. 
- Imprime el valor numérico de la función polinómica. 
- Con el método de Numpy para la creación y evaluación de polinomios `np.poly1d` checa que el cálculo anterior sea el correcto.

#### Definiendo la función

In [99]:
# Definimos una función que evalúa un polinomio en un punto x0 dado un arreglo de coeficientes del polinomio (ordenados de mayor a menor grado) y un punto x0 en el que se evaluará el polinomio (x0 es un número real).

def evaluarPolinomio(coeficientes, x0):
    xn = np.array([x0**i for i in range(len(coeficientes))]) # creamos un arreglo con los valores de x^n
    xn = xn[::-1] # invertimos el arreglo para que el primer elemento sea x^n y el último x^0
    cumprod = np.cumprod([xn, coeficientes],axis=0) # multiplicamos los elementos de xn y coeficientes
    return (sum(cumprod[1])) #sumamos los elementos de la multiplicación

In [98]:
# Ejemplo: si queremos evaluar el polinomio 23x^5 + 54x^4 + 73x^3 + 2x^2 + 7x + 28 en x0 = 56, entonces:
coeficientes = [23,54,73,2,7,28] # coeficientes del polinomio
x0 = 56 # valor de x, para el cual queremos evaluar el polinomio

eval_1 = evaluarPolinomio(coeficientes, x0)
print(eval_1) # imprimimos el resultado de la evaluación

## Ahora vamos a hacer lo mismo con la función de numpy poly1d para comparar resultados

poly = np.poly1d(coeficientes) # creamos un polinomio con los coeficientes
eval_2 = poly(x0)
print(eval_2) # imprimimos el resultado de la evaluación

13210720292
13210720292


In [91]:
# comparamos los resultados de las dos evaluaciones
print(eval == eval_2)
# Resultado: iguales, por lo que ambas funciones realizan la misma tarea

True


### Ejercicio # 3
- Crea una matriz (4 x 3) de números enteros generados aleatoriamente entre 0 y 10. 
- Reemplaza los dos primeros vectores renglón con escalares = 7. 
- Crea un nuevo arreglo (4 x 1) con puros unos y anéxalo con el método `append()` a la matriz anterior. 
- Imprime cada uno de los resultados parciales que vas generando

In [102]:
# Creemos una matriz 4x3 con números aleatorios entre 0 y 10
# (Asumimos que la matriz es de tipo entero)

matriz = np.random.randint(0,10,(4,3))

print(matriz)





[[8 6 2]
 [3 1 4]
 [3 9 9]
 [1 1 8]]
